### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by abbasyadollahi**
### Description
Update License to MIT

### Checklist
- [x] Code compiles correctly
- [x] All tests passing
- [x] There is an open issue linked to this PR
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation (if necessary)

### CODE REVIEW

**Comment by CamiloGarciaLaRotta** [comment]
how come?

**Comment by abbasyadollahi** [comment]
It's really just to standardise the license we use across all repos but if you're against it it's no worries

**Comment by CamiloGarciaLaRotta** [comment]
@alexboii you ok with me keeping it GPLv3?

**Comment by CamiloGarciaLaRotta** [comment]
closing to avoid loose ends

**Pull request closed without merging**
